#!/usr/bin/env python3
"""
export_fde_rules.py — Export FDE steering rules to multi-platform formats.

Generates platform-specific rule files from the canonical FDE steering file
(.kiro/steering/fde.md) so teams using Cursor, Q Developer, Copilot, Cline,
or Claude Code can benefit from FDE methodology guidance.

Usage:
    python3 scripts/export_fde_rules.py              # Export all platforms
    python3 scripts/export_fde_rules.py --verify     # Verify exports are in sync
    python3 scripts/export_fde_rules.py --platform cursor  # Export single platform

Platforms:
    kiro      → .kiro/steering/ (canonical, no export needed)
    q         → .amazonq/rules/fde-workflow.md
    cursor    → .cursor/rules/fde-workflow.mdc
    cline     → .clinerules/fde-workflow.md
    claude    → .claude/fde-workflow.md
    copilot   → .github/fde-instructions.md
    aidlc     → .aidlc-rule-details/fde/fde-quality-gates.md

Exit codes:
    0 — Success (export or verify)
    1 — Verification failed (exports out of sync)
    2 — Source file not found
"""

import hashlib
import json
import sys
from pathlib import Path
from typing import Optional

# ─── Configuration ───────────────────────────────────────────────────────────

SOURCE_FILE = Path(".kiro/steering/fde.md")
HASH_RECORD = Path(".kiro/steering/.fde-export-hash.json")

CURSOR_FRONTMATTER = """---
description: "FDE (Forward Deployed AI Engineer) quality gates and methodology"
alwaysApply: true
---

"""

PLATFORM_TARGETS: dict[str, Path] = {
    "q": Path(".amazonq/rules/fde-workflow.md"),
    "cursor": Path(".cursor/rules/fde-workflow.mdc"),
    "cline": Path(".clinerules/fde-workflow.md"),
    "claude": Path(".claude/fde-workflow.md"),
    "copilot": Path(".github/fde-instructions.md"),
    "aidlc": Path(".aidlc-rule-details/fde/fde-quality-gates.md"),
}

EXPORT_HEADER = """# FDE Quality Gates — Portable Rules
#
# AUTO-GENERATED from .kiro/steering/fde.md
# Do NOT edit this file directly. Run: python3 scripts/export_fde_rules.py
# Source hash: {hash}
#
# This file provides FDE methodology guidance for platforms that cannot
# use Kiro hooks. Gates are advisory (no enforcement) on non-Kiro platforms.
# For full enforcement, use Kiro with the FDE hooks enabled.

"""


# ─── Core Logic ──────────────────────────────────────────────────────────────

def compute_hash(content: str) -> str:
    """Compute SHA-256 hash of content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]


def read_source() -> Optional[str]:
    """Read the canonical FDE steering file."""
    if not SOURCE_FILE.exists():
        return None
    return SOURCE_FILE.read_text(encoding="utf-8")


def strip_frontmatter(content: str) -> str:
    """Remove YAML frontmatter (---...---) from markdown content."""
    if content.startswith("---"):
        end = content.find("---", 3)
        if end != -1:
            content = content[end + 3:].lstrip("\n")
    return content


def generate_export(source_content: str, platform: str) -> str:
    """Generate platform-specific export from source content."""
    source_hash = compute_hash(source_content)
    clean_content = strip_frontmatter(source_content)
    header = EXPORT_HEADER.format(hash=source_hash)

    if platform == "cursor":
        return CURSOR_FRONTMATTER + header + clean_content
    else:
        return header + clean_content


def export_all(source_content: str) -> dict[str, str]:
    """Export to all platforms. Returns dict of platform → file path."""
    source_hash = compute_hash(source_content)
    results: dict[str, str] = {}

    for platform, target_path in PLATFORM_TARGETS.items():
        target_path.parent.mkdir(parents=True, exist_ok=True)
        export_content = generate_export(source_content, platform)
        target_path.write_text(export_content, encoding="utf-8")
        results[platform] = str(target_path)

    # Write hash record for verification
    HASH_RECORD.parent.mkdir(parents=True, exist_ok=True)
    hash_data = {
        "source_hash": source_hash,
        "source_file": str(SOURCE_FILE),
        "exports": {p: str(t) for p, t in PLATFORM_TARGETS.items()},
    }
    HASH_RECORD.write_text(json.dumps(hash_data, indent=2), encoding="utf-8")

    return results


def verify_exports(source_content: str) -> list[str]:
    """Verify all exports are in sync with source. Returns list of errors."""
    errors: list[str] = []
    source_hash = compute_hash(source_content)

    if not HASH_RECORD.exists():
        return ["No export hash record found. Run: python3 scripts/export_fde_rules.py"]

    hash_data = json.loads(HASH_RECORD.read_text(encoding="utf-8"))
    if hash_data.get("source_hash") != source_hash:
        errors.append(
            f"Source has changed since last export. "
            f"Recorded: {hash_data.get('source_hash')}, Current: {source_hash}"
        )

    for platform, target_path in PLATFORM_TARGETS.items():
        if not target_path.exists():
            errors.append(f"Missing export: {target_path} (platform: {platform})")
        else:
            content = target_path.read_text(encoding="utf-8")
            if source_hash not in content:
                errors.append(f"Stale export: {target_path} (hash mismatch)")

    return errors


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main() -> int:
    """CLI entry point."""
    args = sys.argv[1:]
    verify_mode = "--verify" in args
    platform_filter = None

    for i, arg in enumerate(args):
        if arg == "--platform" and i + 1 < len(args):
            platform_filter = args[i + 1]

    # Read source
    source_content = read_source()
    if source_content is None:
        print(f"❌ Source file not found: {SOURCE_FILE}")
        print("   Ensure you're running from the project root.")
        return 2

    source_hash = compute_hash(source_content)

    if verify_mode:
        errors = verify_exports(source_content)
        if errors:
            print(f"❌ Export verification failed ({len(errors)} issue(s)):")
            for err in errors:
                print(f"   • {err}")
            return 1
        print(f"✅ All exports in sync (source hash: {source_hash})")
        return 0

    # Export mode
    if platform_filter:
        if platform_filter not in PLATFORM_TARGETS:
            print(f"❌ Unknown platform: '{platform_filter}' (valid: {sorted(PLATFORM_TARGETS.keys())})")
            return 1
        target_path = PLATFORM_TARGETS[platform_filter]
        target_path.parent.mkdir(parents=True, exist_ok=True)
        export_content = generate_export(source_content, platform_filter)
        target_path.write_text(export_content, encoding="utf-8")
        print(f"✅ Exported to {target_path} (hash: {source_hash})")
        return 0

    # Export all
    results = export_all(source_content)
    print(f"✅ Exported FDE rules to {len(results)} platforms (hash: {source_hash}):")
    for platform, path in results.items():
        print(f"   • {platform:8s} → {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
